import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";
import { DashboardClient } from "./useClientcall";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function InitAuth() {
  return <DashboardClient />;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body
        className="
        min-h-screen flex flex-col m-0 p-0
        bg-linear-to-br from-gray-50 via-white to-gray-100
        dark:from-gray-950 dark:via-gray-900 dark:to-gray-950
        text-gray-900 dark:text-gray-100
        selection:bg-primary/20
      "
      >
        {/* Background Glow */}
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <div className="absolute left-1/2 top-50 h-125 w-125-translate-x-1/2 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute right-0 top-1/3 h-100 w-100 rounded-full bg-blue-500/10 blur-3xl" />
        </div>

        <QueryProvider>
          <InitAuth />
          {/* Main Content */}
          <main className="flex-1 w-full">
            <div
              className="
              
              bg-white/80 dark:bg-gray-900/70
              backdrop-blur-xl
              border border-gray-200/60 dark:border-gray-800/60
              shadow-xl shadow-gray-200/40 dark:shadow-black/40
              transition-all duration-300
              w-full rounded-2xl p-4 sm:p-6 lg:p-8
            "
            >
              {children}
            </div>
          </main>
        </QueryProvider>

        <Toaster
          position="top-right"
          toastOptions={{
            className: "bg-gray-900 text-white border border-gray-700",
          }}
        />
      </body>
    </html>
  );
}
